version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

  db:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
